# Generated by Django 3.1.2 on 2020-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201007_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittrack',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
