# Generated by Django 3.1.2 on 2020-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201008_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittrack',
            name='submit_time',
        ),
        migrations.AlterField(
            model_name='submittrack',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
